on death:
	attacker is a player
	victim is not a player or wither or enderdragon # Spieler und Bosse ausschließen
	set {_i} to "%victim% spawn egg" parsed as an item type
	chance of 0.25%:
		drop {_i} at victim
		send title "§2Glückwunsch!" with subtitle "§d§kaaa §aDu hast ein Spawnei erhalten §d§kaaa" to attacker for 10 seconds
		play sound "ui.toast.challenge_complete" to attacker
		launch trailing flickering star colored purple, yellow, blue, green and red fading to pink at victim with power 0